version: '3' 
services: 
  containeraa: 
    build: 
      context: .
      dockerfile: Dockerfile2
    #image: marwaney/ssh-server
    container_name: container-aa
    networks: 
      - networkaa 

  containerbb: 
    build: 
      context: .
     #le contexte c'est le dossier  
      dockerfile: Dockerfile2
    #image: marwaney/ssh-server 
    container_name: container-bb
    networks: 
      - networkbb 

networks:
  networkaa:
  networkbb: 
    